// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jncylslqdxarrzpczvhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuY3lsc2xxZHhhcnJ6cGN6dmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDcwNDAsImV4cCI6MjA2Njk4MzA0MH0.v8WCzPHJu4texV741J7TvvRxBmeiFMmUMQK9J5jF1Rk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});